services:
  - type: web
    name: shoplex-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 10000 -c serve.json
    envVars:
      - key: NODE_ENV
        value: production